service: email-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    EMAIL_PROVIDER: ${env:EMAIL_PROVIDER}
    EMAIL_USERNAME: ${env:EMAIL_USERNAME}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
  serverless-offline:
    httpPort: 4000